updated pill dropdown component
textkernel/oneui pull request #1300
Opened 2024-10-28 09:34 UTC by AlsasaAmmar

[Update pill dropdown molecule](https://textkernel.atlassian.net/jira/software/c/projects/ONEUI/boards/119?selectedIssue=ONEUI-495)

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. Use imperative, present tense in your commit description ("change", not "changed" or "changes") without uppercases or period (.) at the end.

# Checklist
- [ ] The implementation has been manually tested and complies with Textkernel [browser support guidelines](https://textkernel.com/browser-support/)
- [ ] The implementation complies with [accessibility](CONTIRBUTING.md#accessibility) standards.
- [ ] The component has a [displayName](CONTRIBUTING.md#display-names) defined.
- [ ] The component comes with a detailed [PropTypes](CONTRIBUTING.md#component-props) (and defaultProps) definition.
- [ ] Component PropTypes are sufficiently described / documented.
- [ ] There is [a story](CONTRIBUTING.md#component-showcases) in Storybook.

2024-11-04 14:52 UTC, andrentk requested changes
Update PR title accordingly to the guidelines and redeploy vercel deployment.

2024-11-07 16:32 UTC, andrentk requested changes

2024-11-07 16:32 UTC, andrentk commented on src/components/Pill/Pill.tsx
> -    doneLabel,
you remove it from here but you did not remove it from the props. Also the onClose button js docs are mentioning this done button.

2024-11-07 16:32 UTC, andrentk commented on src/components/Pill/PillDropdown/PillDropdown.scss
> +    max-height: 440px;
If you put loads of content in the dropdown, it will be bigger then the max-height. Add a story that covers that case.

2024-11-07 16:32 UTC, andrentk commented on src/components/Pill/__tests__/__snapshots__/Pill.spec.tsx.snap
> +    donelabel="Done"
this should not appear after the changes

2024-11-12 10:35 UTC, andrentk commented on src/components/Pill/PillDropdown/PillDropdown.scss
> +        overflow-x: auto;
shouldn't this be overflow-y: scroll?

2024-11-21 10:05 UTC, eszthoff commented on src/components/Pill/__tests__/Pill.spec.tsx
> +            expect(screen.getByTitle('Classic')).toBeInTheDocument();
nice. i haven't seen this before

2024-11-21 10:17 UTC, eszthoff commented
I couldn't make the scroll show up. Can you check? Also maybe make the text longer in the story, so it is readily visible.

I wonder is we shouldn't move the DropdownContent element from Pill to PillDropdown. Now the shadow and so on is not visible in the standalone story. 

Lastly I wonder if we still need 3 divs nested in each other in order to render the dropdown, but there might be some reason for this.

2024-11-22 15:54 UTC, eszthoff approved these changes

2024-11-25 09:47 UTC, merged