feat(Checkbox): Add indeterminate state to the Checkbox component
textkernel/oneui pull request #831
Opened 2022-10-03 15:29 UTC by andrentk

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. Use imperative, present tense in your commit description ("change", not "changed" or "changes") without uppercases or period (.) at the end.

# Checklist
- [ ] The implementation has been manually tested and complies with Textkernel [browser support guidelines](https://textkernel.com/browser-support/)
- [ ] The implementation complies with [accessibility](CONTIRBUTING.md#accessibility) standards.
- [ ] The component has a [displayName](CONTRIBUTING.md#display-names) defined.
- [ ] The component comes with a detailed [PropTypes](CONTRIBUTING.md#component-props) (and defaultProps) definition.
- [ ] Component PropTypes are sufficiently described / documented.
- [ ] There is [a story](CONTRIBUTING.md#component-showcases) in Storybook.

2022-10-04 12:33 UTC, eszthoff commented on src/components/Checkbox/Checkbox.tsx
> +            indeterminate,
I think we should assign a default `false` here too.

2022-10-05 15:03 UTC, eszthoff requested changes

2022-10-06 08:14 UTC, andrentk commented on src/components/Checkbox/__tests__/Checkbox.spec.js
> +    it('should render the checked svg when checked and indeterminate are false', () => {
Nice catch!

2022-10-06 09:18 UTC, eszthoff approved these changes

2022-10-06 09:45 UTC, merged