fix: add rest for components
textkernel/oneui pull request #836
Opened 2022-10-11 09:55 UTC by PavelKirvelTextkernel

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. Use imperative, present tense in your commit description ("change", not "changed" or "changes") without uppercases or period (.) at the end.

# Checklist
- [ ] The implementation has been manually tested and complies with Textkernel [browser support guidelines](https://textkernel.com/browser-support/)
- [ ] The implementation complies with [accessibility](CONTIRBUTING.md#accessibility) standards.
- [ ] The component has a [displayName](CONTRIBUTING.md#display-names) defined.
- [ ] The component comes with a detailed [PropTypes](CONTRIBUTING.md#component-props) (and defaultProps) definition.
- [ ] Component PropTypes are sufficiently described / documented.
- [ ] There is [a story](CONTRIBUTING.md#component-showcases) in Storybook.

2022-10-11 10:41 UTC, andrentk commented on src/components/Buttons/Button/Button.tsx
> +    ref?;
I think this can be completely removed, right?

2022-10-11 14:36 UTC, eszthoff requested changes

2022-10-11 14:36 UTC, eszthoff commented on src/components/ButtonGroup/ButtonGroup.tsx
> +            <div {...rest} {...block({ isBlock, ...rest })} role="group">
need to change it in line 45 as well.

2022-10-11 14:36 UTC, eszthoff commented on src/components/Callout/Callout.tsx
> +                    {...elem('closeButton', { context })}
why not adding rest here and in the previous one (line 27), but you do in the next one (MdClose, line 33)?

2022-10-11 14:36 UTC, eszthoff commented on src/components/CandidateAvatar/CandidateAvatar.tsx
> +            {...block({ ...rest })}
there are usage of `elem` here where you removed the props (looking at the previous PR) but you haven't added it back

2022-10-11 14:36 UTC, eszthoff commented on src/components/Checkbox/Checkbox.tsx
> +            <div style={style} {...block({ className, asFlexbox, ...rest })}>
there are usage of elem here where you removed the props (looking at the previous PR) but you haven't added it back

2022-10-12 13:04 UTC, eszthoff commented
reminder from slack conversation:

Heading: ref still defined in Props
SearchButton, Checkbox, FieldWrapper, ref is not typed

2022-10-12 13:32 UTC, eszthoff commented
> reminder from slack conversation:
> 
> Heading: ref still defined in Props SearchButton, Checkbox, FieldWrapper, ref is not typed

It should correspond to the HTMLElement where ref is used. If we pass HTMLElement, but it is a button, then button specific attributes will throw an error. So better to be more specific when possible





[3:26](https://textkernelteam.slack.com/archives/D045KEFU5H6/p1665581207398119)
SearchButton => HTMLButtonElement
[3:27](https://textkernelteam.slack.com/archives/D045KEFU5H6/p1665581246399169)
Checkbox => HTMLInputElement
[3:28](https://textkernelteam.slack.com/archives/D045KEFU5H6/p1665581282575679)
FieldWrapper => HTMLDivElement

2022-10-12 13:35 UTC, eszthoff approved these changes

2022-10-12 13:39 UTC, merged