feat: replace defaultProps with defaultValues
textkernel/oneui pull request #840
Opened 2022-10-18 06:35 UTC by PavelKirvelTextkernel

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. Use imperative, present tense in your commit description ("change", not "changed" or "changes") without uppercases or period (.) at the end.

# Checklist
- [ ] The implementation has been manually tested and complies with Textkernel [browser support guidelines](https://textkernel.com/browser-support/)
- [ ] The implementation complies with [accessibility](CONTIRBUTING.md#accessibility) standards.
- [ ] The component has a [displayName](CONTRIBUTING.md#display-names) defined.
- [ ] The component comes with a detailed [PropTypes](CONTRIBUTING.md#component-props) (and defaultProps) definition.
- [ ] Component PropTypes are sufficiently described / documented.
- [ ] There is [a story](CONTRIBUTING.md#component-showcases) in Storybook.

2022-10-20 08:52 UTC, PavelKirvelTextkernel commented
LocationAutocomplete - when  change to default values test LocationAutocomplete.spec.js just stuck 

LocationSelectorDialogWithGoogleLoader  -    googleMapsApiKey={apiKey} , show warning: TS2783: 'googleMapsApiKey' is specified more than once, so this usage will be overwritten.

SelectButtonGroup.tsx - allow null for two fields 

RangeSlider - not clear which fields should add

2022-10-26 08:39 UTC, mukiienko commented
@PavelKirvelTextkernel did you update the node engine in package.json

2022-10-26 10:59 UTC, PavelKirvelTextkernel commented
@mukiienko Yes, I've done it in this PR: https://github.com/textkernel/oneui/pull/836/files

2022-10-26 14:10 UTC, mukiienko requested changes

2022-10-27 10:26 UTC, eszthoff commented on src/components/Drawer/index.ts
> +export { Drawer } from './Drawer';
yes, that's correct. Otherwise you will have TS errors in the stories, as far as I remember. And they might not show up in the Docs page in Storybook

2022-10-27 13:38 UTC, mukiienko approved these changes

2022-11-02 09:22 UTC, mukiienko approved these changes

2022-11-02 10:15 UTC, merged