feat: rtl tests refactoring
textkernel/oneui pull request #933
Opened 2023-03-31 08:17 UTC by PavelKirvelTextkernel

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. Use imperative, present tense in your commit description ("change", not "changed" or "changes") without uppercases or period (.) at the end.

# Checklist
- [ ] The implementation has been manually tested and complies with Textkernel [browser support guidelines](https://textkernel.com/browser-support/)
- [ ] The implementation complies with [accessibility](CONTIRBUTING.md#accessibility) standards.
- [ ] The component has a [displayName](CONTRIBUTING.md#display-names) defined.
- [ ] The component comes with a detailed [PropTypes](CONTRIBUTING.md#component-props) (and defaultProps) definition.
- [ ] Component PropTypes are sufficiently described / documented.
- [ ] There is [a story](CONTRIBUTING.md#component-showcases) in Storybook.

2023-03-31 13:16 UTC, eszthoff requested changes

2023-04-18 09:57 UTC, PavelKirvelTextkernel commented
https://textkernel.atlassian.net/browse/ONEUI-375

2023-04-19 13:30 UTC, eszthoff requested changes

2023-04-19 13:30 UTC, eszthoff commented on TESTING_LIBRARY_MIGRATION.md
> +await userEvent.type(screen.getByDisplayValue(''), 'Utrecht');
Also, I thought one should call `setup` for the user first. So:
`const user = userEvent.setup()`
see: https://testing-library.com/docs/user-event/intro#writing-tests-with-userevent

2023-04-19 13:37 UTC, PavelKirvelTextkernel commented on TESTING_LIBRARY_MIGRATION.md
>  expect(screen.getByText('value')).toBeDefined();
The idea was to provide different methods for this doc

2023-04-19 13:42 UTC, eszthoff commented on TESTING_LIBRARY_MIGRATION.md
>  expect(screen.getByText('value')).toBeDefined();
Sorry, I don't get it. The before and the after seems to be unrelated. Maybe an equivalent test should be added to the `Before` section, no?

2023-04-20 04:46 UTC, PavelKirvelTextkernel commented on TESTING_LIBRARY_MIGRATION.md
>  expect(screen.getByText('value')).toBeDefined();
:+1:

2023-04-20 08:48 UTC, eszthoff commented on TESTING_LIBRARY_MIGRATION.md
> +expect(wrapper.find('value')).toHaveLength(1);
```suggestion
expect(wrapper.find('Button')).toHaveLength(1);
```

2023-04-20 08:48 UTC, eszthoff commented on TESTING_LIBRARY_MIGRATION.md
> +expect(screen.getByRole('value')).toBeInTheDocument();
```suggestion
expect(screen.getByRole('button')).toBeInTheDocument();
```

2023-04-20 08:48 UTC, eszthoff commented on TESTING_LIBRARY_MIGRATION.md
> +expect(asFragment()).toMatchSnapshot();
```suggestion
```

2023-04-20 08:48 UTC, eszthoff commented on TESTING_LIBRARY_MIGRATION.md
>  expect(component).toMatchSnapshot();
```suggestion
```

2023-04-20 09:12 UTC, PavelKirvelTextkernel commented on TESTING_LIBRARY_MIGRATION.md
> +expect(wrapper.find('value')).toHaveLength(1);
:+1:

2023-04-20 09:12 UTC, PavelKirvelTextkernel commented on TESTING_LIBRARY_MIGRATION.md
> +expect(screen.getByRole('value')).toBeInTheDocument();
:+1:

2023-04-20 09:13 UTC, PavelKirvelTextkernel commented on TESTING_LIBRARY_MIGRATION.md
> +expect(asFragment()).toMatchSnapshot();
:+1:

2023-04-20 09:13 UTC, PavelKirvelTextkernel commented on TESTING_LIBRARY_MIGRATION.md
>  expect(component).toMatchSnapshot();
:+1:

2023-04-20 09:17 UTC, merged