test: migrate SelectButton, SelectButtonGroup tests
textkernel/oneui pull request #970
Opened 2023-05-12 06:46 UTC by PavelKirvelTextkernel

Link [task](https://textkernel.atlassian.net/browse/ONEUI-395)

2023-05-12 13:36 UTC, andrentk commented on src/components/SelectButtonGroup/SelectButtonGroup/__tests__/SelectButtonGroup.spec.tsx
> +    let view;
type missing

2023-05-15 08:59 UTC, PavelKirvelTextkernel commented on src/components/SelectButtonGroup/SelectButtonGroup/__tests__/SelectButtonGroup.spec.tsx
> +    let view;
:+1:

2023-05-16 05:43 UTC, PavelKirvelTextkernel commented on src/components/SelectButtonGroup/SelectButtonGroup/__tests__/SelectButtonGroup.spec.tsx
> +        getButton = (number) => screen.getAllByRole('button')[number];
You mean to change it to 
![image](https://github.com/textkernel/oneui/assets/104063210/aff320d5-9731-4824-a703-40f405083f38)

2023-05-16 09:06 UTC, PavelKirvelTextkernel commented on src/components/SelectButtonGroup/SelectButton/__tests__/SelectButton.spec.tsx
> +    it.skip('should call onChange when Enter key was pressed on it', async () => {
i've fixed it

2023-05-16 09:38 UTC, PavelKirvelTextkernel commented on src/components/SelectButtonGroup/SelectButtonGroup/__tests__/SelectButtonGroup.spec.tsx
> +        getButton = (number) => screen.getAllByRole('button')[number];
:+1:

2023-05-23 15:43 UTC, andrentk requested changes
Remove Please Ignore it from the PR title.

2023-05-29 12:09 UTC, andrentk approved these changes

2023-05-29 12:37 UTC, merged